language: java
jdk:
  - oraclejdk8

install:
  # this is needed to ensure that build is run with maven 3.3.9, so that polyglot projects are supported
  - mvn -N io.takari:maven:wrapper -Dmaven=3.3.9

script:
  # 'mvnw' is the versioned maven wrapper, which was downloaded in the previous install step
  - ./mvnw clean install

after_success:
  - ./mvnw jacoco:report coveralls:report
